Helloworld rust/bump dependencies (#5726)
* Bump versions of the dependencies

This resolves the following error when trying to build the app:

package `socket2 v0.5.5` cannot be built because it requires rustc 1.63 or newer

* Update the documentation

Currently, when following the steps to recreate the sample code,
we will face the following errors when trying to build the app:

error: edition 2021 is unstable and only available with -Z unstable-options.

error: could not compile `proc-macro2`