Fix compile error for Dockerfile
Fix compile error on golang 1.12 .  It doesn't define the method "errors.Is" yet. The error message is  as follows. 
#golang.org/x/net/http2  
src/golang.org/x/net/http2/client_conn_pool.go:305:6: undefined: errors.Is
golang 1.13+ defined the method "errors.Is", It will pass the compile when using golang 1.13+ instead.