Update the glooctl version command (#2186)
```
$ glooctl --version
Error: unknown flag: --version
Usage:
  glooctl [command]

Available Commands:
  add         Adds configuration to a top-level Gloo resource
  check       Checks Gloo resources for errors (requires Gloo running on Kubernetes)
  completion  generate auto completion for your shell
  create      Create a Gloo resource
  dashboard   Open Gloo dashboard
  debug       Debug a Gloo resource (requires Gloo running on Kubernetes)
  delete      Delete a Gloo resource
  edit        Edit a Gloo resource
  get         Display one or a list of Gloo resources
  help        Help about any command
  install     install gloo on different platforms
  proxy       interact with proxy instances managed by Gloo
  remove      remove configuration items from a top-level Gloo resource
  route       subcommands for interacting with routes within virtual services
  uninstall   uninstall gloo
  upgrade     upgrade glooctl binary
  version     Print current version

Flags:
  -c, --config string              set the path to the glooctl config file (default "<home_directory>/.gloo/glooctl-config.yaml")
      --consul-address string      address of the Consul server. Use with --use-consul (default "127.0.0.1:8500")
      --consul-datacenter string   Datacenter to use. If not provided, the default agent datacenter is used. Use with --use-consul
      --consul-root-key string     key prefix for for Consul key-value storage. (default "gloo")
      --consul-scheme string       URI scheme for the Consul server. Use with --use-consul (default "http")
      --consul-token string        Token is used to provide a per-request ACL token which overrides the agent's default token. Use with --use-consul
  -h, --help                       help for glooctl
  -i, --interactive                use interactive mode
      --kubeconfig string          kubeconfig to use, if not standard one
      --use-consul                 use Consul Key-Value storage as the backend for reading and writing config (VirtualServices, Upstreams, and Proxies)

Use "glooctl [command] --help" for more information about a command.

$ glooctl version
Client: {"version":"1.3.3"}
```